from django.urls import path, include
from .views import (
    MenuItemViewSet,
    CategoryViewSet,
    GroupManagerViewSet,
    GroupDeliveryCrewViewSet,
    CartViewSet,
    OrderViewSet,
    CustomUserViewSet
)

urlpatterns = [
    path('users', CustomUserViewSet.as_view({'get':'list','post':'create'}), name='users'),
    path('categories', CategoryViewSet.as_view({'get':'list','post':'create'}), 
         name='categories'),
    path('categories/<int:pk>', 
         CategoryViewSet.as_view({'get':'retrieve','put':'update','patch':'partial_update','delete':'destroy'}), 
         name='categories-detail'),
    path('menu-items', MenuItemViewSet.as_view({'get':'list','post':'create'}), 
         name='menu-items'),
    path('menu-items/<int:pk>', 
         MenuItemViewSet.as_view({'get':'retrieve','put':'update','patch':'partial_update','delete':'destroy'}), 
         name='menu-items-detail'),
    path('groups/manager/users', GroupManagerViewSet.as_view({'get':'list','post':'create'}), 
         name='manager-view'),
    path('groups/manager/users/<int:pk>', 
         GroupManagerViewSet.as_view({'get':'retrieve','delete':'destroy'}), 
         name='manager-view-detail'),
    path('groups/delivery-crew/users', 
         GroupDeliveryCrewViewSet.as_view({'get':'list','post':'create'}), 
         name='delivery-crew-view'),
    path('groups/delivery-crew/users/<int:pk>', 
         GroupDeliveryCrewViewSet.as_view({'get':'retrieve','delete':'destroy'}), 
         name='delivery-crew-view-detail'),
    path('cart/menu-items', CartViewSet.as_view({'get':'list','post':'create','delete':'destroy'}),
            name='cart'),
    path('orders', OrderViewSet.as_view({'get':'list','post':'create'}),
            name='orders'),
    path('orders/<int:pk>', 
         OrderViewSet.as_view({'get':'retrieve','put':'update','delete':'destroy','patch':'partial_update'}),
            name='orders-detail'),
    path('cart/orders', OrderViewSet.as_view({'get':'list','post':'create'}),
            name='orders'),
    path('cart/orders/<int:pk>', 
         OrderViewSet.as_view({'get':'retrieve','put':'update','delete':'destroy','patch':'partial_update'}),
            name='orders-detail'),
]